# Generated by Django 5.2.8 on 2025-12-12 10:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='property',
            name='properties__status_a1c8f0_idx',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='status',
            new_name='listing_status',
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(default='Apartment', max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='size',
            field=models.IntegerField(default=0, help_text='Square meters'),
        ),
        migrations.AddField(
            model_name='property',
            name='workflow_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('available', 'Available'), ('rented', 'Rented')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['listing_status', 'approved', 'is_featured'], name='properties__listing_321306_idx'),
        ),
    ]
